cmake_policy(SET CMP0012 NEW)
cmake_minimum_required(VERSION 3.14)

if(NOT DEFINED OUTPUT_FILE OR NOT DEFINED TARGET_SIZE)
    message(FATAL_ERROR "OUTPUT_FILE and TARGET_SIZE are required")
endif()

set(CHUNK "")
set(SEED "ngapain-dibongkar-ini-sampah-decoy-idinganteng-anjing-")
while(1)
    string(LENGTH "${CHUNK}" CHUNK_LEN)
    if(CHUNK_LEN GREATER_EQUAL 65536)
        break()
    endif()
    string(APPEND CHUNK "${SEED}${CHUNK_LEN};")
endwhile()
string(SUBSTRING "${CHUNK}" 0 65536 CHUNK)

file(WRITE "${OUTPUT_FILE}" "")
math(EXPR FULL_CHUNKS "${TARGET_SIZE} / 65536")
math(EXPR REMAINDER "${TARGET_SIZE} % 65536")
foreach(INDEX RANGE 1 ${FULL_CHUNKS})
    file(APPEND "${OUTPUT_FILE}" "${CHUNK}")
endforeach()
if(REMAINDER GREATER 0)
    string(SUBSTRING "${CHUNK}" 0 ${REMAINDER} TAIL)
    file(APPEND "${OUTPUT_FILE}" "${TAIL}")
endif()
file(SIZE "${OUTPUT_FILE}" ACTUAL_SIZE)
if(NOT ACTUAL_SIZE EQUAL TARGET_SIZE)
    message(FATAL_ERROR "decoy blob size ${ACTUAL_SIZE}, expected ${TARGET_SIZE}")
endif()